### ISSUE TITLE
Android版歌单太大无法导出歌单

### ISSUE THREAD

**Issue by adigest** [listen1/listen1_chrome_extension#605]
`
2021-06-18 09:51:53.006 22285-22357/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.listen1.app, PID: 22285
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1251048 bytes
        at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:127)
        at com.facebook.react.modules.clipboard.ClipboardModule.setString(ClipboardModule.java:62)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:219)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1251048 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:532)
        at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:307)
        at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:125)
        at com.facebook.react.modules.clipboard.ClipboardModule.setString(ClipboardModule.java:62) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:900) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:219) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232) 
        at java.lang.Thread.run(Thread.java:929) 
`

**Comment by adigest** [comment]
最好能做成和PC版类似的可以到出到listen1_backup.json这样的文件中，
然后又可以从listen1_backup.json中恢复，
这样多端同步起来也会更方便一点，
尤其歌多了以后
-_-
